#!/bin/sh

export CORSOCXX_PATH=${HOME}/C++
export CORSOCXX_UTIL=${CORSOCXX_PATH}
cd `dirname $0`
export ANALYSIS_PATH=`/bin/pwd`

#####################################################################

export LIB_NAME=AnalysisFramework
echo "compile " ${LIB_NAME}
cd ${ANALYSIS_PATH}/${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} \
-o ${ANALYSIS_PATH}/lib${LIB_NAME}.so *.cc

export LIB_NAME=AnalysisObjects
echo "compile " ${LIB_NAME}
cd ${ANALYSIS_PATH}/${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} \
-o ${ANALYSIS_PATH}/lib${LIB_NAME}.so *.cc

export LIB_NAME=AnalysisUtilities
echo "compile " ${LIB_NAME}
cd ${ANALYSIS_PATH}/${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} \
-o ${ANALYSIS_PATH}/lib${LIB_NAME}.so *.cc

#####################################################################

cd ${ANALYSIS_PATH}/AnalysisPlugins

export LIB_NAME=EventDump
echo "compile " ${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} \
-o ${ANALYSIS_PATH}/lib${LIB_NAME}.so ${LIB_NAME}.cc

export LIB_NAME=ParticleLifeTime
echo "compile " ${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} \
`root-config --cflags`                                              \
-o ${ANALYSIS_PATH}/lib${LIB_NAME}.so ${LIB_NAME}.cc

export LIB_NAME=ParticleMass
echo "compile " ${LIB_NAME}
rm -f ${ANALYSIS_PATH}/lib${LIB_NAME}.so
c++ -Wall -fPIC -shared -I. -I ${CORSOCXX_UTIL} -I ${ANALYSIS_PATH} -I. `root-config --cflags`  -o ${ANALYSIS_PATH}/lib${LIB_NAME}.so ${LIB_NAME}.cc `root-config --libs`            


#####################################################################

cd ${ANALYSIS_PATH}

export EXE_NAME=runDump
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
c++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL} -I. `root-config --cflags` \
-o ${EXE_NAME} dum.cc `root-config --libs`  -L ${ANALYSIS_PATH} -Wl,-rpath,${ANALYSIS_PATH}/--no-as-needed         \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lParticleLifeTime -lEventDump

export EXE_NAME=runBG
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
c++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}   -I. `root-config --cflags`       \
-o ${EXE_NAME} dum.cc `root-config --libs`  -L ${ANALYSIS_PATH} -Wl,-rpath,${ANALYSIS_PATH}/--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lParticleMass -lParticleLifeTime `root-config --libs`

export EXE_NAME=runPlot
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
c++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}   -I. `root-config --cflags`        \
-o ${EXE_NAME} dum.cc `root-config --libs` -L ${ANALYSIS_PATH} -Wl,-rpath,${ANALYSIS_PATH}/--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lParticleLifeTime -lParticleMass `root-config --libs`

export EXE_NAME=runAll
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
c++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}  -I. `root-config --cflags`       \
-o ${EXE_NAME} dum.cc `root-config --libs`  -L ${ANALYSIS_PATH} -Wl,-rpath,${ANALYSIS_PATH}/--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lEventDump -lParticleMass -lParticleLifeTime `root-config --libs`

